version: "3.4"
services:
  neko:
    image: "m1k1o/neko:brave"
    restart: "unless-stopped"
    shm_size: "4gb"
    ports:
      - "80:8080"
      - "52000-52100:52000-52100/udp"
    cap_add:
      - SYS_ADMIN
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: yang
      NEKO_PASSWORD_ADMIN: babi
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: 1