version: "3.7"
services:
  samba:
    image: dockurr/samba:latest
    container_name: samba
    environment:
      NAME: "Shares"
      USER: "altan"
      PASS: "altan"
      RW: "false"
    ports:
      - 445:445
    network_mode: host
    volumes:
      - /share:/storage
      - /sharexs:/storage2
      - /home/altan/runtipi/apps/altan-runtipi/samba-runtipi/smb.conf:/etc/samba/smb.conf
